/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

//Created by Maria Chrysafis
#include <iostream>
#include <fstream>

#include <iostream>
#include <algorithm>
#include <vector>
#include <map>
#include <set>
#include <queue>
#include <unordered_map>
#include <unordered_set>
#include <cmath>
using namespace std;
class Problem2FruitFeast {
public:
  void solve(std::istream& in, std::ostream& out) {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    int T,A,B;
    in >> T >> A >> B;
    bool pos[T + 1];
    pos[0] = true;
    for(int i = 1; i <= T; i++){
      pos[i] = false;
    }
    for(int i = 0; i <= T; i++){
      if(i - A >= 0){
        pos[i] = pos[i - A] || pos[i];
      }
      if(i - B >= 0){
        pos[i] = pos[i] || pos[i - B];
      }
    }
    int pref[T];
    pref[0] = 0;
    for(int i = 1; i <= T; i++){
      pref[i] = max(pref[i - 1], pos[i] * i);
    }
    int myMax = 0;
    for(int i = 0; i <= T; i++){
      if(!pos[i]){
        continue;
      }
      myMax = max(i/2 + pref[T - i/2],myMax);
    }
    out << myMax << endl;
  }
};


int main() {
	Problem2FruitFeast solver;
	std::ifstream in("feast.in");
	std::ofstream out("feast.out");
	solver.solve(in, out);
	return 0;
}
