/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
using namespace std;
class D12KGame {
public:
    void f(std::istream& in, std::ostream& out) {
      int n,k;
      in >> n >> k;
      if(k % 3 != 0){
        if(n % 3 == 0){
          out << "Bob" << endl;
          return;
        }else{
          out << "Alice" << endl;
          return;
        }
      }
      int period = k + 1;
      n = n % period;
      if(n == k){
        out << "Alice" << endl;
        return;
      }
      if(n % 3 == 0){
        out << "Bob" << endl;
        return;
      }else{
        out << "Alice" << endl;
        return;
      }
    }
	void solve(std::istream& in, std::ostream& out) {
	  int t;
	  in >> t;
	  while(t--){
	    f(in, out);
	  }
	}
};
int main() {
	D12KGame solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
