/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <vector>
using namespace std;
class DGameWithArray {
public:
	void solve(std::istream& in, std::ostream& out) {
	  int N,S;
	  in >> N >> S;
	  if(N * 2 > S){
	    out << "NO" << endl;
	    return;
	  }
      out << "YES" << endl;
	  for(int i = 0; i < N - 1; i++){
	    out << 2 << " ";
	  }
	  out << S - 2 * (N - 1) << endl;
	  out << S - 1 << endl;
	}
};


int main() {
	DGameWithArray solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
