/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */
 
#include <iostream>
#include <fstream>
 
#include <iostream>
#include <algorithm>
#include <set>
using namespace std;
class ABovineDilemma {
public:
    void f(std::istream& in, std::ostream& out) {
      int n;
      in >> n;
      int arr[n];
      for(int i = 0; i < n; i++){
        in >> arr[i];
      }
      sort(arr,arr + n);
      set<int> s;
      for(int i = 0; i < n; i++){
        for(int j = i + 1; j < n; j++){
          s.insert(arr[j] - arr[i]);
        }
      }
      out << s.size() << endl;
    }
	void solve(std::istream& in, std::ostream& out) {
	  int t;
	  in >> t;
	  while(t--){
	    f(in,out);
	  }
	}
};
 
 
int main() {
	ABovineDilemma solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
