/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <algorithm>
using namespace std;
class EFourSegments {
public:
	void solve(std::istream& in, std::ostream& out) {
	  int t;
	  in >> t;
	  while(t--){
	    int a[4];
	    for(int i = 0; i < 4; i++){
	      in >> a[i];
	    }
	    sort(a, a + 4);
	    out << a[0] * a[2] << endl;
	  }
	}
};


int main() {
	EFourSegments solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
