    /**
     * code generated by JHelper
     * More info: https://github.com/AlexeyDmitriev/JHelper
     * @author
     */
     
    #include <iostream>
    #include <fstream>
     
    #include <iostream>
    using namespace std;
    class AStrangePartition {
    public:
    	void solve(std::istream& in, std::ostream& out) {
    	  int t;
    	  in >> t;
    	  while(t--){
    	    long long n;
    	    in >> n;
    	    long long x;
    	    in >> x;
    	    long long sum = 0;
    	    long long beuty = 0;
    	    for(int i = 0; i < n; i++){
    	      long long a;
    	      in >> a;
    	      sum += a;
    	      beuty += a/x + (a % x != 0);
    	    }
    	    out << sum/x + (sum % x != 0) << " " << beuty << endl;
    	  }
    	}
    };
     
     
    int main() {
    	AStrangePartition solver;
    	std::istream& in(std::cin);
    	std::ostream& out(std::cout);
    	solver.solve(in, out);
    	return 0;
    }
