/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
using namespace std;
class CFloorAndMod {
public:
  void f(istream &in, ostream &out){
    long long x,y;
    in >> x >> y;
    long long sum = 0;
    for(long long i = 1; i * (i + 2) <= x; i++){
      long long pos1 = x/i - (i + 2);
      long long pos2 = y - (i + 1);
      if(pos1 < 0){
        pos1 = 0;
        sum--;
      }
      if(pos2 < 0){
        pos2 = 0;
        sum--;
      }
      sum += min(pos1, pos2);
      sum++;
    }
    out << sum << endl;
  }
  void solve(std::istream &in, std::ostream &out) {
    int t;
    in >> t;
    while(t--){
      f(in, out);
    }
  }
};


int main() {
  ios_base::sync_with_stdio(false);
  cin.tie(NULL);
	CFloorAndMod solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
