/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */
 
#include <iostream>
#include <fstream>
 
#include <iostream>
#include <algorithm>
using namespace std;
class AArena {
public:
  bool valid(std::istream &in, std::ostream &out){
    int n;
    in >> n;
    int arr[n];
    for(int i = 0; i < n; i++){
      in >> arr[i];
    }
    sort(arr, arr + n);
    int x = arr[0];
    int cntr = 0;
    for(int i = 0; i < n; i++){
      if(arr[i] == x){
        cntr++;
      }
    }
    out << n - cntr << endl;
    return cntr;
  }
  void solve(std::istream &in, std::ostream &out) {
    int t;
    in >> t;
    while(t--){
      valid(in, out);
    }
  }
};
 
 
int main() {
	AArena solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
