/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
using namespace std;
class Problem2IWouldWalk500Miles {
public:
  void solve(std::istream &in, std::ostream &out) {
    int N, K;
    in >> N >> K;
    //(N - K, N)
    long long l1 = 84 * (K - 1) + 48 * N;
    out << 2019201997 - l1 << endl;
    //2019201997
  }
};


int main() {
  ios_base::sync_with_stdio(false);
  cin.tie(NULL);
	Problem2IWouldWalk500Miles solver;
	std::ifstream in("walk.in");
	std::ofstream out("walk.out");
	solver.solve(in, out);
	return 0;
}
