/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <vector>
using namespace std;
class BAbbreviateFox {
public:
	void solve(std::istream& in, std::ostream& out) {
	  int n;
	  in >> n;
	  string s;
	  in >> s;
	  string t = "";
	  for(int i = s.length() - 1; i >= 0; i--){
	    t += s[i];
	    if(t.length() < 3){
	      continue;
	    }
	    if(t[t.length() - 1] == 'f' && t[t.length() - 2] == 'o' && t[t.length() - 3] == 'x' ){
	      t.pop_back();
	      t.pop_back();
	      t.pop_back();
	    }
	  }
	  out << t.length() << endl;
	}
};


int main() {
	BAbbreviateFox solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
