/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

//Created by Maria Chrysafis
#include <iostream>
#include <fstream>

#include <algorithm>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cmath>
using namespace std;
class BookShop {
public:
  void solve(std::istream &in, std::ostream &out) {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    int n, x;
    in >> n >> x;
    int h[n];
    int s[n];
    for (int i = 0; i < n; i++) {
      in >> h[i];
    }
    for (int i = 0; i < n; i++) {
      in >> s[i];
    }
    int DP[x + 1];
    int INF = pow(10, 9) + 7;
    for (int i = 0; i <= x; i++) {
      DP[i] = -INF;
    }
    DP[0] = 0;
    // DP[price] -> max pages
    for (int j = 0; j < n; j++) {
      for (int i = x; i >= 0; i--) {
        if (i + h[j] > x)
          continue;
        DP[i + h[j]] = max(DP[i] + s[j], DP[i + h[j]]);
      }
    }
    int myMax = 0;
    for (int i = 0; i <= x; i++) {
      myMax = max(myMax,DP[i]);
    }
    out << myMax << endl;
  }
};


int main() {
	BookShop solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
