/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <algorithm>
#include <fstream>

#include <iostream>
#pragma GCC target ("avx2")
#pragma GCC optimization ("O3")
#pragma GCC optimization ("unroll-loops")
#pragma optimization_level 3
#pragma GCC optimize("Ofast,no-stack-protector,unroll-loops,fast-math,O3")
#pragma GCC target("sse,sse2,sse3,ssse3,sse4,popcnt,abm,mmx,avx,tune=native")
using namespace std;
class MakeTheSumEven {
  public:
  void f(std::istream& in, std::ostream& out) {
    int n;
    in >> n;
    long long arr[n];
    long long sum = 0;
    for(int i = 0; i < n; i++){
      in >> arr[i];
      sum += arr[i];
    }
    if(sum % 2 == 0){
      out << 0 << endl;
      return;
    }
    for(long long x: arr){
      if(x == 2){
          out << 1 << endl;
        return;
      }
    }
    out << -1 << '\n';
  }
    void solve(std::istream& in, std::ostream& out) {
      int t;
      in >> t;
      while(t--){
        f(in, out);
      }
    }
};


int main() {
	MakeTheSumEven solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
